# Generated by Django 3.2.2 on 2023-04-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20230430_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buy_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
