# Generated by Django 3.2.2 on 2023-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_alter_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='previous_close',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='week_52_high',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='week_52_low',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='ytd_change',
        ),
        migrations.AddField(
            model_name='quote',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
